// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhaSachDotNet.Entity;

#nullable disable

namespace NhaSachDotNet.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230905135034_AddTheLoai")]
    partial class AddTheLoai
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NhaSachDotNet.Entity.Sachs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("giaBan")
                        .HasColumnType("float");

                    b.Property<double>("giaBanDau")
                        .HasColumnType("float");

                    b.Property<string>("gioiThieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngonNgu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<int>("soTrang")
                        .HasColumnType("int");

                    b.Property<long>("tacgiaid")
                        .HasColumnType("bigint");

                    b.Property<string>("tenSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("theLoaiId")
                        .HasColumnType("bigint");

                    b.Property<string>("thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("theLoaiId");

                    b.ToTable("sach");
                });

            modelBuilder.Entity("NhaSachDotNet.Entity.TheLoai", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("tenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("NhaSachDotNet.Entity.Sachs", b =>
                {
                    b.HasOne("NhaSachDotNet.Entity.TheLoai", "theLoai")
                        .WithMany("dsSach")
                        .HasForeignKey("theLoaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("theLoai");
                });

            modelBuilder.Entity("NhaSachDotNet.Entity.TheLoai", b =>
                {
                    b.Navigation("dsSach");
                });
#pragma warning restore 612, 618
        }
    }
}
